export const GENRE_CATEGORIES = [
  { id: 'ambient',    label: 'Ambient / Drone' },
  { id: 'techno',     label: 'Techno / House' },
  { id: 'idm',        label: 'IDM / Experimental' },
  { id: 'industrial', label: 'Industrial / Noise' },
  { id: 'darkwave',   label: 'Synthwave / Darkwave' },
  { id: 'triphop',    label: 'Trip-Hop / Downtempo' },
  { id: 'dnb',        label: 'Drum & Bass / Jungle' },
  { id: 'classical',  label: 'Classical / Orchestral' },
];

const GENRE_MAP = {
  'electronic music': ['idm'],
  'electronic': ['idm'],
  'techno': ['techno'],
  'house music': ['techno'],
  'house': ['techno'],
  'minimal techno': ['techno'],
  'acid house': ['techno'],
  'acid techno': ['techno'],
  'detroit techno': ['techno'],
  'deep house': ['techno'],
  'tech house': ['techno'],
  'dub techno': ['techno', 'ambient'],
  'microhouse': ['techno'],
  'ambient music': ['ambient'],
  'ambient': ['ambient'],
  'dark ambient': ['ambient'],
  'drone music': ['ambient'],
  'drone': ['ambient'],
  'new age': ['ambient'],
  'space music': ['ambient'],
  'idm': ['idm'],
  'intelligent dance music': ['idm'],
  'experimental music': ['idm'],
  'experimental': ['idm'],
  'experimental electronic': ['idm'],
  'glitch': ['idm'],
  'electroacoustic': ['idm'],
  'musique concrète': ['idm'],
  'industrial music': ['industrial'],
  'industrial': ['industrial'],
  'noise music': ['industrial'],
  'noise': ['industrial'],
  'power electronics': ['industrial'],
  'death industrial': ['industrial'],
  'ebm': ['industrial', 'darkwave'],
  'electronic body music': ['industrial', 'darkwave'],
  'synthwave': ['darkwave'],
  'darkwave': ['darkwave'],
  'coldwave': ['darkwave'],
  'post-punk': ['darkwave'],
  'synthpop': ['darkwave'],
  'synth-pop': ['darkwave'],
  'new wave': ['darkwave'],
  'minimal wave': ['darkwave'],
  'gothic rock': ['darkwave'],
  'electropunk': ['darkwave'],
  'trip hop': ['triphop'],
  'trip-hop': ['triphop'],
  'downtempo': ['triphop'],
  'chillout': ['triphop'],
  'lounge': ['triphop'],
  'dub': ['triphop'],
  'reggae fusion': ['triphop'],
  'drum and bass': ['dnb'],
  'drum & bass': ['dnb'],
  'jungle': ['dnb'],
  'breakcore': ['dnb'],
  'breakbeat': ['dnb'],
  'uk garage': ['dnb'],
  'dubstep': ['dnb'],
  'grime': ['dnb'],
  'footwork': ['dnb'],
  'juke': ['dnb'],
  'classical music': ['classical'],
  'classical': ['classical'],
  'orchestral': ['classical'],
  'opera': ['classical'],
  'symphony': ['classical'],
  'chamber music': ['classical'],
  'baroque music': ['classical'],
  'baroque': ['classical'],
  'romantic music': ['classical'],
  'impressionist music': ['classical'],
  'minimalism': ['classical'],
  'minimalist music': ['classical'],
  'contemporary classical': ['classical'],
  'neoclassical': ['classical'],
  'piano music': ['classical'],
  'choral music': ['classical'],
  'art music': ['classical'],
  'concerto': ['classical'],
  'sonata': ['classical'],
  'cantata': ['classical'],
  'oratorio': ['classical'],
  'post-minimalism': ['classical'],
  'serial music': ['classical'],
  'atonal music': ['classical'],
  'twelve-tone technique': ['classical'],
};

export function categorizeGenres(rawGenres) {
  const categories = new Set();
  for (const raw of rawGenres) {
    const normalized = raw.toLowerCase().trim();
    if (GENRE_MAP[normalized]) {
      GENRE_MAP[normalized].forEach(c => categories.add(c));
    } else {
      for (const [key, cats] of Object.entries(GENRE_MAP)) {
        if (normalized.includes(key) || key.includes(normalized)) {
          cats.forEach(c => categories.add(c));
        }
      }
    }
  }
  return [...categories];
}
